//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawzand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacttbl
    {
        public string phone { get; set; }
        public string email { get; set; }
        public string fb { get; set; }
        public string othersocial { get; set; }
        public string youtube { get; set; }
        public int ID { get; set; }
    }
}
