//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawzand.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lawzandEntities1 : DbContext
    {
        public lawzandEntities1()
            : base("name=lawzandEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<gallerytbl> gallerytbls { get; set; }
        public virtual DbSet<partnertbl> partnertbls { get; set; }
        public virtual DbSet<projecttbl> projecttbls { get; set; }
        public virtual DbSet<servicetbl> servicetbls { get; set; }
        public virtual DbSet<slidertbl> slidertbls { get; set; }
        public virtual DbSet<langtbl> langtbls { get; set; }
        public virtual DbSet<sudo> sudoes { get; set; }
        public virtual DbSet<infotbl> infotbls { get; set; }
        public virtual DbSet<projectview> projectviews { get; set; }
        public virtual DbSet<contacttbl> contacttbls { get; set; }
    }
}
