//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lawzand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicetbl
    {
        public decimal serviceId { get; set; }
        public string servicename { get; set; }
        public string servicepic { get; set; }
        public string servicecontent { get; set; }
        public string thumb { get; set; }
        public int lang { get; set; }
    }
}
